name: Dev tests
on:
  workflow_call:
    secrets:

jobs:

  run:
    # Will read on PR dashboard as 'Deploy / DevTests / ubuntu'
    # Action dashboard identified by 'Dev tests'
    # Requirement settings identified as 'DevTests / ubuntu'
    name: ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Global Setup
        run: |
          python -m pip install -U pip
          pip install pytest
      - name: Install local checkout
        run: pip install --no-cache-dir .

      - name: Display installed packages and their sources for debugging
        run: pip list

      - name: Run basic file read test
        run: nwb_benchmarks run --bench time_remote_file_reading.HDF5PyNWBRemfilePreloadedNoCacheFileReadBenchmark.time_read_hdf5_pynwb_remfile_preloaded_no_cache

      - name: Run basic slicing test
        run: nwb_benchmarks run --bench time_remote_slicing.HDF5PyNWBRemfilePreloadedNoCacheContinuousSliceBenchmark.time_slice
